import assert from 'node:assert/strict';
import path from 'node:path';
import test from 'node:test';
import {JSDOM} from 'jsdom';
import {createServer} from 'vite';
import {readFacts} from '@foundation/core';
import {EVENTS, ROOT} from '../helpers/project-fixture.mjs';

function installDom() {
  const dom = new JSDOM('<!doctype html><html><body></body></html>', {url: 'http://localhost'});
  Object.assign(globalThis, {window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, Element: dom.window.Element, Node: dom.window.Node, Event: dom.window.Event, MouseEvent: dom.window.MouseEvent, MutationObserver: dom.window.MutationObserver, getComputedStyle: dom.window.getComputedStyle, IS_REACT_ACT_ENVIRONMENT: true});
  Object.defineProperty(globalThis, 'navigator', {value: dom.window.navigator, configurable: true});
  globalThis.ResizeObserver = class {observe() {} unobserve() {} disconnect() {}};
  globalThis.matchMedia = () => ({matches: false, addEventListener() {}, removeEventListener() {}});
  globalThis.requestAnimationFrame = (callback) => setTimeout(() => callback(Date.now()), 0);
  globalThis.cancelAnimationFrame = clearTimeout;
  dom.window.HTMLElement.prototype.getAnimations = () => [];
  dom.window.HTMLElement.prototype.scrollIntoView = () => {};
  return dom;
}

test('预览侧栏无旧内容 Tabs、Select 和原始 Textarea，连续展示页面逻辑', async (t) => {
  const dom = installDom();
  let documentScrollRequests = 0;
  dom.window.HTMLElement.prototype.scrollIntoView = () => { documentScrollRequests += 1; };
  const vite = await createServer({root: path.join(ROOT, 'apps/management-center'), configFile: path.join(ROOT, 'apps/management-center/vite.config.js'), optimizeDeps: {noDiscovery: true}, server: {middlewareMode: true}});
  t.after(async () => { await vite.close(); dom.window.close(); });
  const {act, createElement} = await import('react');
  const {createRoot} = await import('react-dom/client');
  const {PreviewSidebar} = await vite.ssrLoadModule('/src/features/context-panel/preview-sidebar.jsx');
  const {TooltipProvider} = await vite.ssrLoadModule('/src/components/ui/tooltip.jsx');
  const facts = readFacts(EVENTS);
  const container = document.createElement('div'); document.body.append(container);
  const root = createRoot(container);
  await act(async () => root.render(createElement(PreviewSidebar, {model: {pages: facts.pages.items, relations: facts.relations.items, interactions: facts.interactions.items}, pageId: 'page_events_home'})));
  assert.match(container.textContent, /当前事件/);
  assert.match(container.textContent, /从哪里进入/);
  assert.match(container.textContent, /可以去哪里/);
  assert.match(container.textContent, /点击事件/);
  assert.equal(container.querySelector('[role="tablist"]'), null);
  assert.equal(container.querySelector('textarea'), null);
  assert.equal(container.querySelector('[data-slot="select-trigger"]'), null);
  await act(async () => root.render(createElement(PreviewSidebar, {model: {pages: facts.pages.items, relations: facts.relations.items, interactions: facts.interactions.items}, pageId: 'page_events_manage', selectedEvent: {id: 'event_launch', state: 'archived'}})));
  assert.match(container.textContent, /所选事件的运行状态/);
  assert.match(container.textContent, /已归档/);
  assert.match(container.textContent, /可执行状态操作：恢复/);
  assert.doesNotMatch(container.textContent, /事实状态|confirmed|verified/);
  const navigation = []; const previews = []; let copied = '';
  const objectName = 'Foundation 验证项目当前事件只展示仍在进行中的事件；归档与删除操作集中在管理页。新增事件管理事件重要事件Prompt 010 工程结构';
  const object = {inspectorId: 'component:component_event_action:event_action_manage', name: objectName, role: 'button', componentId: 'component_event_action', instanceId: 'event_action_manage', registeredComponent: true, pageId: 'page_events_home', path: ['main', 'header', 'button'], ancestorIds: ['dom:main', 'dom:main/header'], tree: [{inspectorId: 'dom:main', name: '页面主体', role: 'main', registeredComponent: false, summary: 'main', children: [{inspectorId: 'dom:main/header', name: '页头', role: 'header', registeredComponent: false, summary: 'header', children: [{inspectorId: 'component:component_event_action:event_action_manage', name: '管理事件', role: 'button', registeredComponent: true, summary: 'component_event_action', children: []}]}]}], layout: {display: 'inline-flex'}, style: {fontSize: '13px'}, relatedLogic: facts.relations.items.filter((item) => item.trigger === '管理事件'), usageLocations: [{pageId: 'page_events_home', instanceId: 'event_action_manage'}], gaps: [], factsUpdatedAt: '2026-08-29T10:00:00.000Z'};
  await act(async () => root.render(createElement(TooltipProvider, null, createElement(PreviewSidebar, {view: 'object', model: {project: facts.foundation, pages: facts.pages.items, relations: facts.relations.items}, pageId: 'page_events_home', inspectedObject: object, onNavigate: (value) => navigation.push(value), onPreview: (value) => previews.push(value), onCopyTask: (value) => { copied = value; }}))));
  assert.match(container.textContent, /已锁定对象/);
  const objectHeading = container.querySelector('.inspector-heading h2');
  assert.equal(objectHeading.textContent, objectName);
  assert.match(objectHeading.className, /\btruncate\b/);
  assert.equal(objectHeading.getAttribute('data-slot'), 'tooltip-trigger');
  assert.equal(objectHeading.tabIndex, 0);
  assert.equal(objectHeading.getAttribute('title'), null, '完整标题应由 shadcn Tooltip 展示而不是原生 title');
  await act(async () => { objectHeading.focus(); await new Promise((resolve) => setTimeout(resolve, 0)); });
  assert.equal(document.querySelector('[data-slot="tooltip-content"]').textContent, objectName);
  const objectIdentity = container.querySelector('[data-object-identity]');
  assert.equal(objectIdentity.textContent, 'component_event_action · event_action_manage');
  assert.match(objectIdentity.className, /\btruncate\b/);
  assert.equal(objectIdentity.getAttribute('data-slot'), 'tooltip-trigger');
  assert.equal(objectIdentity.tabIndex, 0);
  assert.equal(objectIdentity.getAttribute('title'), null, '完整技术标识应由 shadcn Tooltip 展示而不是原生 title');
  await act(async () => { objectHeading.blur(); objectIdentity.focus(); await new Promise((resolve) => setTimeout(resolve, 0)); });
  assert.equal(document.querySelector('[data-slot="tooltip-content"]').textContent, 'component_event_action · event_action_manage');
  assert.match(container.textContent, /默认修改范围/);
  assert.equal(container.querySelectorAll('[role="tree"]').length, 1);
  const tree = container.querySelector('[role="tree"]');
  assert.equal(tree.dataset.fileTree, 'collapsible');
  assert.equal(tree.querySelectorAll('[data-inspector-tree-item]').length, 3);
  const selectedItem = tree.querySelector('[data-inspector-tree-item][aria-selected="true"]');
  assert.ok(selectedItem);
  assert.match(selectedItem.className, /bg-secondary/);
  await act(async () => selectedItem.dispatchEvent(new MouseEvent('mouseover', {bubbles: true})));
  assert.deepEqual(previews.at(-1), {inspectorId: object.inspectorId});
  await act(async () => selectedItem.dispatchEvent(new MouseEvent('mouseout', {bubbles: true, relatedTarget: tree})));
  assert.equal(previews.at(-1), null);
  const folderToggles = [...tree.querySelectorAll('[data-inspector-tree-toggle]')];
  assert.equal(folderToggles.length, 2);
  assert.equal(tree.querySelectorAll('.lucide-folder, .lucide-file').length, 0, '文件树只保留展开收起箭头');
  assert.equal(documentScrollRequests, 0, '文件树定位不得滚动外层检查对象面板');
  const rootToggle = folderToggles.find((button) => button.getAttribute('aria-label') === '收起 页面主体');
  const headerToggle = folderToggles.find((button) => button.getAttribute('aria-label') === '收起 页头');
  assert.ok(rootToggle);
  assert.ok(headerToggle);
  const rootRow = rootToggle.closest('.inspector-file-tree-row');
  assert.match(rootRow.className, /items-center/);
  assert.match(rootRow.className, /gap-0\.5/);
  assert.match(tree.querySelector('[role="group"]').className, /ml-5/);
  assert.match(rootToggle.querySelector('.lucide-chevron-right').getAttribute('class'), /group-data-panel-open:rotate-90/);
  await act(async () => headerToggle.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  await act(async () => rootToggle.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  assert.equal(rootToggle.hasAttribute('data-panel-open'), false);
  assert.deepEqual(navigation, [], '展开收起不得同时触发对象定位');
  await act(async () => rootToggle.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  const collapsedHeaderToggle = tree.querySelector('button[aria-label="展开 页头"]');
  assert.ok(collapsedHeaderToggle);
  await act(async () => collapsedHeaderToggle.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  const leaf = [...tree.querySelectorAll('[data-inspector-tree-item]')].find((button) => button.textContent.includes('管理事件'));
  assert.ok(leaf);
  const leafRow = leaf.closest('.inspector-file-tree-row');
  assert.match(leafRow.className, /items-center/);
  assert.match(leafRow.className, /gap-0\.5/);
  assert.match(leafRow.querySelector('[data-inspector-tree-spacer]').className, /size-6/);
  assert.match(leafRow.querySelector('[data-inspector-tree-spacer]').className, /shrink-0/);
  await act(async () => leaf.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  assert.deepEqual(navigation, [{inspectorId: 'component:component_event_action:event_action_manage'}], '逐级展开后的叶节点必须可点击定位');
  assert.equal(container.querySelector('input'), null);
  const copy = [...container.querySelectorAll('button')].find((button) => button.textContent.includes('复制'));
  await act(async () => copy.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  const menuItems = [...document.querySelectorAll('[data-slot="dropdown-menu-item"]')];
  assert.deepEqual(menuItems.map((item) => item.textContent), ['完整对象上下文', '身份与层级', '相关逻辑', '布局与样式', '使用、影响与缺口']);
  await act(async () => menuItems[1].dispatchEvent(new MouseEvent('click', {bubbles: true})));
  assert.match(copied, /Foundation 检查对象上下文 · 身份与层级/);
  assert.match(copied, /object stable identity/);
  assert.doesNotMatch(copied, /outerHTML|computedStyle/i);
  await act(async () => root.unmount());
});
