import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {makeTempDirectory,projectFixturePath} from '../helpers/project-fixture.mjs';
import {applyLifecycleForTest,applyProjectForTest} from '../helpers/test-authorization.mjs';
import {createLifecyclePlan} from '../../packages/core/install-contract.mjs';
import {createProjectAuthorityPlan} from '../../packages/core/project-authority.mjs';
import {synchronizeProject} from '../../packages/core/project-sync.mjs';
import {readFacts} from '../../packages/core/facts.mjs';
import {inspectProjectDeliveryFiles} from '../../packages/core/project-delivery.mjs';
import {inspectProjectStructure,inspectSemanticCoverage} from '../../packages/core/project-coverage.mjs';
import {prepareWorkbenchSnapshot} from '../../apps/management-center/src/server/workbench-snapshot.mjs';
test('047R2 normal sync owns round, derives static and React objects, keeps unknown and external replacement pending',{timeout:180000},()=>{
 const base=makeTempDirectory('047r2-round-'),candidate=fs.realpathSync(process.env.FOUNDATION_047_CANDIDATE),manifest=JSON.parse(fs.readFileSync(path.join(candidate,'manifest.json'))),installationRoot=path.join(base,'installation');
 applyLifecycleForTest(createLifecyclePlan({operation:'install',targetRoot:installationRoot,sandboxRoot:base,targetVersion:manifest.productVersion,candidate:{path:candidate,manifestHash:manifest.candidateHash,runtimeHash:manifest.files.find(f=>f.path===manifest.runtime.path).sha256,bytes:manifest.totalBytes,version:manifest.productVersion}}));
 const project=projectFixturePath(base,'ordinary');fs.mkdirSync(project,{recursive:true});assert(applyProjectForTest(createProjectAuthorityPlan({operation:'enable',project,installationRoot,continuousSync:'grant',includePreview:true})).ok);
 const sync=options=>{const result=synchronizeProject({project,installationRoot,...options});assert(!['failed','conflict'].includes(result.state),JSON.stringify(result));return result;};
 sync({roundAction:'begin',taskId:'ordinary'});const start=readFacts(project).project.contextLifecycle.currentRoundId;
 fs.writeFileSync(path.join(project,'index.html'),`<main><button onclick="document.querySelector('dialog').showModal()">新增</button><dialog><button onclick="this.closest('dialog').close()">取消</button></dialog></main>`);
 fs.writeFileSync(path.join(project,'Search.jsx'),"import {useState} from 'react';export function Search(){const [query,setQuery]=useState('');return <main><input onChange={e=>setQuery(e.target.value)}/>{query ? <p>结果</p> : <p>空结果</p>}</main>}");
 sync({roundAction:'finish',taskId:'ordinary'});
 const facts=readFacts(project),inventory=inspectProjectStructure(project);assert.equal(facts.project.contextLifecycle.currentRoundId,start);assert.equal(facts.pages.items.length,1);assert.equal(facts.components.items.length,1);assert.equal(inspectSemanticCoverage(facts,inventory).state,'recorded-not-reviewed');assert.equal(inspectProjectDeliveryFiles({project,installationRoot}).round.state,'observed');
 const snapshot=prepareWorkbenchSnapshot({project,installationRoot});assert(snapshot.sourceScenes[facts.components.items[0].id+':definition']);
 const oldTime=facts.components.items[0].updatedAt;
 sync({roundAction:'begin',taskId:'format'});fs.writeFileSync(path.join(project,'Search.jsx'),"// equivalent format\n"+fs.readFileSync(path.join(project,'Search.jsx'),'utf8').replace('return <main>','return  <main>'));
 sync({roundAction:'finish',taskId:'format'});const formatted=prepareWorkbenchSnapshot({project,installationRoot});assert.equal(formatted.semanticRevision,snapshot.semanticRevision);assert.equal(formatted.resourceRevision,snapshot.resourceRevision);assert.notEqual(formatted.observationRevision,snapshot.observationRevision);assert.equal(readFacts(project).components.items[0].updatedAt,oldTime);
 const before=fs.readFileSync(path.join(project,'.foundation/facts/pages.json'));assert.equal(sync({}).mutationPerformed,false);assert.deepEqual(fs.readFileSync(path.join(project,'.foundation/facts/pages.json')),before);
 const owner=readFacts(project).pages.items[0].id;sync({roundAction:'begin',taskId:'identity',identityActions:[{kind:'create',ownerId:owner,sourceFile:'index.html',objectId:'new-dialog'}]});const birth=readFacts(project).project.contextLifecycle.identities[0].incarnation;const pageText=fs.readFileSync(path.join(project,'index.html'),'utf8').replace('<dialog>',`<dialog data-foundation-owner-id="${owner}" data-foundation-object-id="new-dialog" data-foundation-incarnation="${birth}">`);fs.writeFileSync(path.join(project,'index.html'),pageText);sync({roundAction:'finish',taskId:'identity'});assert.equal(readFacts(project).project.contextLifecycle.identities[0].state,'active');
 fs.unlinkSync(path.join(project,'index.html'));fs.writeFileSync(path.join(project,'index.html'),pageText);const rejected=synchronizeProject({project,installationRoot,roundAction:'begin',taskId:'late-intent',identityActions:[{kind:'retain',incarnation:birth}]});assert.equal(rejected.state,'failed');assert.match(rejected.error.message,/出生身份/);
 sync({roundAction:'begin',taskId:'replacement',identityActions:[{kind:'retire',incarnation:birth},{kind:'create',ownerId:owner,sourceFile:'index.html',objectId:'new-dialog'}]});const second=readFacts(project).project.contextLifecycle.identities[1].incarnation;assert.notEqual(second,birth);fs.writeFileSync(path.join(project,'index.html'),pageText.replace(birth,second));sync({roundAction:'finish',taskId:'replacement'});assert.equal(readFacts(project).project.contextLifecycle.identities[0].state,'removed');assert.equal(readFacts(project).project.contextLifecycle.identities[1].state,'active');
 fs.writeFileSync(path.join(project,'unreported.jsx'),'export function Hidden(){return <button>未登记</button>}');const unknown=inspectProjectDeliveryFiles({project,installationRoot});assert.equal(unknown.deliveryReady,false);assert.equal(unknown.assessment.aggregate,'pending');assert(unknown.issues.some(issue=>issue.code==='ROUND_UNACCOUNTED_INPUT'));
 console.log('047R2 round evidence='+base);
});
