import assert from 'node:assert/strict';
import path from 'node:path';
import test from 'node:test';
import {JSDOM} from 'jsdom';
import {createServer} from 'vite';
import {projectAssets, readFacts, relationsVersion} from '@foundation/core';
import {EVENTS, ROOT} from '../helpers/project-fixture.mjs';

test('顶栏左侧显示当前项目名称，右侧统一导航在三种工作区间切换并保留页面身份', async (t) => {
  const dom = new JSDOM('<!doctype html><html><body></body></html>', {url: 'http://127.0.0.1:4317/', pretendToBeVisual: true});
  Object.assign(globalThis, {window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, Element: dom.window.Element, Node: dom.window.Node, SVGElement: dom.window.SVGElement, Event: dom.window.Event, MouseEvent: dom.window.MouseEvent, MutationObserver: dom.window.MutationObserver, getComputedStyle: dom.window.getComputedStyle, IS_REACT_ACT_ENVIRONMENT: true});
  Object.defineProperty(globalThis, 'navigator', {value: dom.window.navigator, configurable: true});
  Object.defineProperty(dom.window.navigator, 'clipboard', {value: {writeText: async () => {}}, configurable: true});
  dom.window.HTMLElement.prototype.getBoundingClientRect = () => ({x: 0, y: 0, left: 0, top: 0, right: 1200, bottom: 760, width: 1200, height: 760, toJSON() { return this; }});
  dom.window.HTMLElement.prototype.getAnimations = () => [];
  globalThis.ResizeObserver = class {constructor(callback) { this.callback = callback; } observe() {} unobserve() {} disconnect() {}};
  globalThis.matchMedia = () => ({matches: false, addEventListener() {}, removeEventListener() {}});
  globalThis.requestAnimationFrame = (callback) => setTimeout(() => callback(Date.now()), 0); globalThis.cancelAnimationFrame = (id) => clearTimeout(id);
  dom.window.ResizeObserver = globalThis.ResizeObserver; dom.window.matchMedia = globalThis.matchMedia; dom.window.requestAnimationFrame = globalThis.requestAnimationFrame; dom.window.cancelAnimationFrame = globalThis.cancelAnimationFrame;
  const facts = readFacts(EVENTS); const pages = facts.pages.items.map((page) => ({...page, route: page.preview}));
  dom.window.__FOUNDATION_MODEL__ = {project: facts.foundation, pages, relations: facts.relations.items, relationsVersion: relationsVersion(facts.relations), components: facts.components.items, assets: projectAssets(facts), changes: facts.changes.items, interactions: facts.interactions.items, entryPage: 'page_events_home', preview: {allowedOrigins: ['self']}};
  dom.window.__FOUNDATION_WRITE_NONCE__ = 'test-nonce';
  const vite = await createServer({root: path.join(ROOT, 'apps/management-center'), configFile: path.join(ROOT, 'apps/management-center/vite.config.js'), optimizeDeps: {noDiscovery: true}, server: {middlewareMode: true}});
  t.after(async () => { await vite.close(); dom.window.close(); });
  const {act, createElement} = await import('react'); const {createRoot} = await import('react-dom/client');
  const {WorkspaceApp} = await vite.ssrLoadModule('/src/workspace/workspace-app.jsx');
  const container = document.createElement('div'); document.body.append(container); const root = createRoot(container);
  await act(async () => root.render(createElement(WorkspaceApp)));
  const settleWorkspace = async (ready) => {
    for (let attempt = 0; attempt < 20 && !ready(); attempt += 1) await act(async () => new Promise((resolve) => setTimeout(resolve, 10)));
    assert.equal(ready(), true, '按需工作区应在限定时间内完成加载');
  };
  await settleWorkspace(() => container.textContent.includes('当前事件'));
  assert.match(container.textContent, /当前事件/);
  const header = container.querySelector('.topbar');
  const navigation = header.querySelector('[data-slot="navigation-menu"]');
  const projectIdentity = header.querySelector('.topbar-project');
  assert.ok(projectIdentity);
  assert.equal(projectIdentity.textContent, facts.foundation.name);
  assert.equal(projectIdentity.getAttribute('title'), facts.foundation.name);
  assert.equal(projectIdentity.classList.contains('text-base'), true);
  assert.equal(projectIdentity.classList.contains('font-medium'), true);
  assert.equal(header.childElementCount, 3);
  assert.equal(header.firstElementChild, projectIdentity);
  assert.equal(header.children[1], navigation);
  assert.equal(header.querySelectorAll('[data-slot="navigation-menu-link"]').length, 3);
  assert.deepEqual([...header.querySelectorAll('[data-slot="navigation-menu-link"]')].map((link) => link.textContent), ['预览搭建', '逻辑搭建', '资产管理']);
  const themeButton = header.querySelector('[data-theme-toggle]');
  assert.equal(header.lastElementChild, themeButton);
  assert.equal(themeButton?.tagName, 'BUTTON');
  assert.equal(themeButton?.classList.contains('group/button'), true, '主题入口必须复用现有 shadcn Button 样式与交互基类');
  assert.equal(themeButton?.getAttribute('aria-label'), '切换到暗模式');
  assert.equal(themeButton?.getAttribute('aria-pressed'), 'false');
  assert.match(header.textContent, new RegExp(facts.foundation.name));
  assert.doesNotMatch(header.textContent, /Foundation 工作台|project_foundation-events/);
  assert.equal(header.querySelector('[role="tablist"]'), null);
  assert.equal([...header.querySelectorAll('[data-slot="navigation-menu-link"]')].find((link) => link.textContent === '预览搭建').getAttribute('aria-current'), 'page');
  const contextTabs = [...container.querySelectorAll('[role="tab"]')];
  assert.equal(contextTabs.find((tab) => tab.getAttribute('aria-selected') === 'true').textContent, '页面逻辑');
  const inspectorButton = container.querySelector('button[aria-label="检查预览对象"]');
  const descriptor = {inspectorId: 'component:component_event_action:event_action_manage', name: '管理事件', role: 'button', componentId: 'component_event_action', instanceId: 'event_action_manage', registeredComponent: true};
  const inspected = {version: 1, inspectorId: descriptor.inspectorId, pageId: 'page_events_home', name: '管理事件', role: 'button', componentId: 'component_event_action', instanceId: 'event_action_manage', registeredComponent: true, path: ['main', 'header', 'button'], ancestorIds: ['dom:main', 'dom:main/header'], tree: [{inspectorId: 'dom:main', name: 'main', role: 'main', componentId: null, instanceId: null, registeredComponent: false, summary: 'main', children: [{...descriptor, summary: 'component_event_action', children: []}]}], hierarchy: {parent: null, current: descriptor, children: []}, layout: {display: 'inline-flex'}, style: {color: 'rgb(0, 0, 0)'}};
  const iframeWindow = container.querySelector('#preview-frame').contentWindow;
  const outbound = [];
  iframeWindow.postMessage = (message, origin) => outbound.push({message, origin});
  await act(async () => window.dispatchEvent(new dom.window.MessageEvent('message', {origin: window.location.origin, source: iframeWindow, data: {namespace: 'ai-product-foundation-preview', kind: 'preview-ready', pageId: 'page_events_home', route: '/events', object: inspected}})));
  assert.deepEqual(outbound.at(-1)?.message, {namespace: 'ai-product-foundation-preview', kind: 'theme-changed', theme: 'light'});
  await act(async () => themeButton.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  assert.equal(document.documentElement.classList.contains('dark'), true);
  assert.equal(document.documentElement.dataset.theme, 'dark');
  assert.equal(window.localStorage.getItem('ai-product-foundation-theme'), 'dark');
  assert.equal(themeButton.getAttribute('aria-label'), '切换到亮模式');
  assert.equal(themeButton.getAttribute('aria-pressed'), 'true');
  assert.deepEqual(outbound.at(-1)?.message, {namespace: 'ai-product-foundation-preview', kind: 'theme-changed', theme: 'dark'});
  const objectContextTab = [...container.querySelectorAll('[role="tab"]')].find((tab) => tab.textContent === '检查对象');
  await act(async () => objectContextTab.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  const mainTreeItem = [...container.querySelectorAll('[data-inspector-tree-item]')].find((item) => item.textContent.includes('main'));
  await act(async () => mainTreeItem.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  assert.deepEqual(outbound.slice(-2).map(({message}) => message.kind), ['inspect-mode-changed', 'inspect-navigate']);
  assert.equal(outbound.at(-1).message.inspectorId, 'dom:main');
  const mainDescriptor = {inspectorId: 'dom:main', name: 'main', role: 'main', componentId: null, instanceId: null, registeredComponent: false};
  const inspectedMain = {...inspected, inspectorId: 'dom:main', name: 'main', role: 'main', componentId: null, instanceId: null, registeredComponent: false, path: ['main'], ancestorIds: [], hierarchy: {parent: null, current: mainDescriptor, children: [descriptor]}, layout: {display: 'block'}, style: {color: 'rgb(1, 2, 3)'}};
  await act(async () => window.dispatchEvent(new dom.window.MessageEvent('message', {origin: window.location.origin, source: iframeWindow, data: {namespace: 'ai-product-foundation-preview', kind: 'inspect-selected', object: inspectedMain}})));
  assert.equal(container.querySelector('.inspector-heading h2').textContent, 'main');
  assert.equal(container.querySelector('[data-inspector-tree-item][aria-selected="true"]').textContent.includes('main'), true);
  await act(async () => container.querySelector('button[aria-label="检查预览对象"]').dispatchEvent(new MouseEvent('click', {bubbles: true})));
  const pageContextTab = [...container.querySelectorAll('[role="tab"]')].find((tab) => tab.textContent === '页面逻辑');
  await act(async () => pageContextTab.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  await act(async () => container.querySelector('button[aria-label="检查预览对象"]').dispatchEvent(new MouseEvent('click', {bubbles: true})));
  assert.equal(contextTabs.find((tab) => tab.getAttribute('aria-selected') === 'true').textContent, '页面逻辑');
  await act(async () => window.dispatchEvent(new dom.window.MessageEvent('message', {origin: window.location.origin, source: iframeWindow, data: {namespace: 'ai-product-foundation-preview', kind: 'inspect-selected', object: inspected}})));
  assert.equal([...container.querySelectorAll('[role="tab"]')].find((tab) => tab.getAttribute('aria-selected') === 'true').textContent, '检查对象');
  assert.match(container.textContent, /已锁定对象/);
  await act(async () => pageContextTab.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  const assetLink = [...header.querySelectorAll('[data-slot="navigation-menu-link"]')].find((link) => link.textContent === '资产管理');
  await act(async () => assetLink.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  await settleWorkspace(() => Boolean(container.querySelector('.asset-management-workspace')));
  assert.match(container.textContent, /资产管理只读投影/);
  assert.equal(assetLink.getAttribute('aria-current'), 'page');
  const previewLink = [...container.querySelectorAll('[data-slot="navigation-menu-link"]')].find((link) => link.textContent === '预览搭建');
  await act(async () => previewLink.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  await settleWorkspace(() => Boolean(container.querySelector('.workspace')));
  assert.match(container.textContent, /从哪里进入/);
  const logicLink = [...container.querySelectorAll('[data-slot="navigation-menu-link"]')].find((link) => link.textContent === '逻辑搭建');
  await act(async () => logicLink.dispatchEvent(new MouseEvent('click', {bubbles: true})));
  await settleWorkspace(() => container.querySelectorAll('.page-flow-node').length === 3);
  assert.equal(logicLink.getAttribute('aria-current'), 'page');
  assert.equal(container.querySelectorAll('.page-flow-node').length, 3);
  assert.ok(container.querySelector('.page-flow-node[data-page-id="page_events_home"].is-current'));
  await act(async () => root.unmount());
});
