import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {inspectProjectDeliveryFiles} from '../../packages/core/project-delivery.mjs';
import {FACT_FILES} from '../../packages/core/facts.mjs';import {sha256} from '../../packages/core/install-contract.mjs';
function docsProject(){const base=path.resolve('.tmp/047r2');fs.mkdirSync(base,{recursive:true});const root=fs.mkdtempSync(path.join(base,'round-'));fs.mkdirSync(path.join(root,'.foundation/facts'),{recursive:true});fs.mkdirSync(path.join(root,'.foundation/identity'),{recursive:true});fs.writeFileSync(path.join(root,'.foundation/identity/project.json'),JSON.stringify({schemaVersion:'1.0.0',projectId:'round-project'}));fs.writeFileSync(path.join(root,'guide.md'),'只更新维护说明。\n');const task={id:'docs',name:'维护说明',source:'user-request',status:'draft',updatedAt:'2026-09-20T00:00:00.000Z',verificationStatus:'unverified',implementationMapping:'guide.md',implementationSha256:sha256(fs.readFileSync(path.join(root,'guide.md'))),deliveryScope:{schemaVersion:'2.0.0',taskId:'docs',revision:1,platform:'document',deliverable:'维护说明',depth:'presentation',included:['文档'],excluded:['界面'],layoutPolicy:{mode:'not-applicable',source:'guide.md#L1-L1',reason:'仅文字'},sourceRefs:[{id:'req',kind:'user-request',ref:'guide.md#L1-L1'}],items:[{requirementId:'docs',description:'维护说明',factIds:['docs'],sourceRefIds:['req'],requiredEvidenceDimensions:[],applicability:{state:'not-applicable',source:'guide.md#L1-L1',reason:'仅文档'}}]}};for(const kind of FACT_FILES)fs.writeFileSync(path.join(root,'.foundation/facts',kind+'.json'),JSON.stringify({schemaVersion:'0.1.0',kind,items:kind==='changes'?[task]:[]}));return root;}
test('047R2 permanent regression: unreported new JSX cannot inherit document N/A',()=>{const project=docsProject();assert.equal(inspectProjectDeliveryFiles({project}).deliveryReady,true);fs.writeFileSync(path.join(project,'Unreported.jsx'),'export function Extra(){return <main><button>新操作</button></main>}');const result=inspectProjectDeliveryFiles({project});assert.equal(result.deliveryReady,false);assert(result.issues.some(issue=>issue.code==='ROUND_UNACCOUNTED_INPUT'));});
test('047R2 actual inventory captures additions, deletions, dependency bytes and JS formatting equivalence',async()=>{const {captureProjectRoundInputs,diffRoundInputs}=await import('../../packages/core/project-context-round.mjs');const project=docsProject();fs.writeFileSync(path.join(project,'View.jsx'),'export function View(){return <main>你好</main>}');const before=captureProjectRoundInputs(project);fs.writeFileSync(path.join(project,'View.jsx'),'// formatting\nexport function View() {\n  return <main>你好</main>;\n}\n');fs.writeFileSync(path.join(project,'shared.css'),'button{color:red}');fs.unlinkSync(path.join(project,'guide.md'));const after=captureProjectRoundInputs(project),changes=diffRoundInputs(before,after);assert.deepEqual(changes.map(x=>[x.path,x.kind]),[['guide.md','deleted'],['shared.css','added'],['View.jsx','bytes-only']]);assert.notEqual(before.byteDigest,after.byteDigest);});
test('047R2 ordinary static expressions generate dialog state relationships without supplied semantic answers',async()=>{const {inspectProjectStructure,attachObservedStructure,inspectSemanticCoverage}=await import('../../packages/core/project-coverage.mjs');const project=docsProject();fs.writeFileSync(path.join(project,'index.html'),`<main><header><button onclick="document.querySelector('dialog').showModal()">新增</button></header><dialog><input name="标题"><button onclick="this.closest('dialog').close()">取消</button></dialog></main>`);const inventory=inspectProjectStructure(project),batch=attachObservedStructure({sources:inventory.sources,documents:[{kind:'pages',upserts:[{id:'home',implementationMapping:'index.html'}]}]},inventory),facts={pages:{items:batch.documents[0].upserts}};assert(facts.pages.items[0].sourceStructure.semantics.nodes.some(node=>node.name==='弹窗打开'));assert.equal(inspectSemanticCoverage(facts,inventory).state,'recorded-not-reviewed');facts.pages.items[0].sourceStructure.semantics.relations=facts.pages.items[0].sourceStructure.semantics.relations.filter(edge=>edge.type==='contains');assert.equal(inspectSemanticCoverage(facts,inventory).state,'pending');});
test('047R2 controlled birth, planned cross-owner move and retirement never reuse an incarnation',async()=>{const {beginObjectLifetimes,finishObjectLifetimes,resolveObjectLocator}=await import('../../packages/core/object-identity.mjs');let records=beginObjectLifetimes([],[{kind:'create',objectId:'save',instanceKey:'one',ownerId:'page1',sourceFile:'a.jsx'}]);const birth=records[0].incarnation;const object={ownerId:'page1',incarnation:birth,persistentId:'save',instanceKey:'one',file:'a.jsx'};records=finishObjectLifetimes(records,[object],[{path:'a.jsx',physical:'before',sha256:'a'}]);assert.equal(records[0].state,'active');const external=finishObjectLifetimes(records,[object],[{path:'a.jsx',physical:'recreated',sha256:'a'}]);assert.equal(external[0].state,'unverified');records=beginObjectLifetimes(records,[{kind:'move',incarnation:birth,ownerId:'page2',sourceFile:'b.jsx'}]);records=finishObjectLifetimes(records,[{...object,ownerId:'page2',file:'b.jsx'}],[{path:'b.jsx',physical:'moved',sha256:'b'}]);assert.equal(records[0].incarnation,birth);assert.equal(records[0].ownerId,'page2');records=finishObjectLifetimes(beginObjectLifetimes(records,[{kind:'retire',incarnation:birth}]),[],[]);records=beginObjectLifetimes(records,[{kind:'create',objectId:'save',instanceKey:'one',ownerId:'page2',sourceFile:'b.jsx'}]);assert.notEqual(records[1].incarnation,birth);assert.equal(resolveObjectLocator({projectId:'p',kind:'persistent',persistentId:'save',instanceKey:'one',generation:birth},[{persistentId:'save',instanceId:'one',identityGeneration:records[1].incarnation}],{projectId:'p'}).state,'invalid');});

test('047R2 source scene binds actual export and fixed props, ignores arbitrary adapters, rejects top-level effects',async()=>{
 const {prepareSourceScene}=await import('../../packages/core/source-scene.mjs'),{analyzeSourcesInWorker}=await import('../../packages/core/source-analysis.mjs');
 const project=docsProject();fs.writeFileSync(path.join(project,'Card.jsx'),"import React from 'react';export function Card({label}){return <button>{label}</button>}");
 const d=analyzeSourcesInWorker({project,entryRoots:['Card.jsx']}).definitions.find(d=>d.name==='Card');
 const asset={id:'card',implementationMapping:'Card.jsx',assetModel:{binding:{file:d.file,export:'Card',declarationKind:d.declarationKind,anchor:d.anchor},configuration:[{key:'label',kind:'string'}],previewScenarios:[]},usageLocations:[{instanceId:'one',bindingId:'usage',configuration:{label:'One'}}]};const facts={components:{items:[asset]}},scenario={id:'one',kind:'instance',definitionId:'card',instanceId:'one',adapter:'forged.html'};
 const first=prepareSourceScene({project,facts,asset,scenario});assert(first.plan.inputs.some(input=>input.path==='Card.jsx'));assert.equal(first.plan.configuration.label,'One');assert(!first.plan.inputs.some(input=>input.path==='forged.html'));
 fs.writeFileSync(path.join(project,'Card.jsx'),"// layout\nimport React from 'react';\nexport function Card({label}) {\n return <button>{label}</button>;\n}\n");const formatted=prepareSourceScene({project,facts,asset,scenario});assert.equal(formatted.renderDigest,first.renderDigest);assert.notEqual(formatted.digest,first.digest);
 asset.usageLocations[0].configuration.label='Two';assert.notEqual(first.digest,prepareSourceScene({project,facts,asset,scenario}).digest);
 asset.assetModel.binding.export='Wrong';assert.throws(()=>prepareSourceScene({project,facts,asset,scenario}),/导出/);asset.assetModel.binding.export='Card';
 fs.appendFileSync(path.join(project,'Card.jsx'),'\ndocument.body.append(document.createElement("main"));');assert.throws(()=>prepareSourceScene({project,facts,asset,scenario}),/副作用/);
});
test('047R2 React state and conditional expressions generate independent coverage obligations',async()=>{
 const {inspectProjectStructure,attachObservedStructure,inspectSemanticCoverage}=await import('../../packages/core/project-coverage.mjs');const project=docsProject();fs.writeFileSync(path.join(project,'Search.jsx'),"import {useState} from 'react';export function Search(){const [query,setQuery]=useState('');return <main><input onChange={e=>setQuery(e.target.value)}/>{query ? <p>结果</p> : <p>空结果</p>}</main>}");const inventory=inspectProjectStructure(project);const batch=attachObservedStructure({sources:inventory.sources,documents:[{kind:'components',upserts:[{id:'search',implementationMapping:'Search.jsx'}]}]},inventory);const facts={components:{items:batch.documents[0].upserts}};assert.equal(inspectSemanticCoverage(facts,inventory).state,'recorded-not-reviewed');const graph=facts.components.items[0].sourceStructure.semantics,branch=inventory.obligations.find(item=>item.kind==='state-branch');graph.relations=graph.relations.filter(edge=>!edge.sourceKeys.includes(branch.key));assert.equal(inspectSemanticCoverage(facts,inventory).state,'pending');
});
