import {hasCurrentOwnerEvidence,DELIVERY_DIMENSIONS} from '../../packages/core/project-delivery.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {inspectModuleExports} from '../../scripts/module-probe-values.mjs';import {advanceProjectObservation,captureProjectRoundInputs} from '../../packages/core/project-context-round.mjs';import {planStaticPreview} from '../../packages/core/static-preview-plan.mjs';import {prepareSourceScene} from '../../packages/core/source-scene.mjs';import {analyzeSourcesInWorker} from '../../packages/core/source-analysis.mjs';
const base=path.resolve('.tmp/047r3');fs.mkdirSync(base,{recursive:true});const temp=()=>fs.mkdtempSync(path.join(base,'short-'));
const observation=(sha,physical=sha)=>({files:[{path:'view.jsx',sha256:sha,semanticSha256:sha,physical,kind:'runtime-candidate'}],byteDigest:sha,physicalDigest:physical,unknown:[],previewResources:[]});
test('047R3 observation never accepts import, preflight or later changes; history survives no-op and rebegin',()=>{let state=advanceProjectObservation(null,observation('a'));assert.equal(state.pendingChanges[0].origin,'import-pending');state=advanceProjectObservation(state,observation('b'),{origin:'preflight'});assert.deepEqual(state.pendingChanges[0].history.map(x=>x.after),['a','b']);const again=advanceProjectObservation(state,observation('b'),{origin:'begin'});assert.deepEqual(again.pendingChanges,state.pendingChanges);state=advanceProjectObservation(again,observation('c'),{origin:'read'});assert.equal(state.pendingChanges[0].before,null);assert.equal(state.pendingChanges[0].after.sha256,'c');});
test('047R3 module probe classifies primitives, rejects cycles/getters and keeps nested functions visible',()=>{let calls=0;const getter={};Object.defineProperty(getter,'danger',{enumerable:true,get(){calls++;throw Error('不得执行')}});const cycle={};cycle.self=cycle;const result=inspectModuleExports({symbol:Symbol.for('react.fragment'),empty:undefined,big:10n,cycle,getter,writer:{writeSecret(){return 'body'}}});assert.equal(calls,0);assert(result.filter(x=>['symbol','empty','big'].includes(x.name)).every(x=>x.sourceHash&&!x.unclassified));assert(result.find(x=>x.name==='cycle').unclassified);assert(result.find(x=>x.name==='getter').unclassified);assert.equal(result.find(x=>x.name==='writer').functions[0].path,'writeSecret');});
test('047R3 actual module audit accepts Symbol but still rejects raw writers and unclassified getters',()=>{for(const negative of [false,true]){const root=temp(),app=path.join(root,'payload/app');fs.mkdirSync(app,{recursive:true});fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify({candidateHash:'fixture'}));fs.writeFileSync(path.join(app,'sample.mjs'),negative?`import fs from 'node:fs';export function dangerous(){fs.writeFileSync('/not-executed','x')}export const getter=Object.defineProperty({},'x',{get(){throw Error('no')}});`:`export const symbol=Symbol.for('fragment');export const empty=undefined;export const big=10n;`);const result=spawnSync(process.execPath,['scripts/candidate-module-boundary-audit.mjs','--candidate',root],{encoding:'utf8',env:process.env});assert.equal(result.status,negative?1:0,result.stderr);const parsed=JSON.parse(result.stdout);if(negative){assert(parsed.unknownOrForbidden.some(x=>x.code==='UNGATED_EXPORTED_WRITER_PATH'));assert(parsed.unknownOrForbidden.some(x=>x.code==='MODULE_EXPORT_UNCLASSIFIED'));}}});
test('047R3 static plan maps relative CSS/image/JS atomically, preserves routes, rejects collision and escape',()=>{const root=temp();fs.mkdirSync(path.join(root,'pages'));fs.writeFileSync(path.join(root,'pages/index.html'),'<main>普通页面</main><link href="../site.css" rel="stylesheet"><script src="../app.js"></script>');fs.writeFileSync(path.join(root,'site.css'),'body{background:url(icon.svg)}');fs.writeFileSync(path.join(root,'icon.svg'),'<svg/>');fs.writeFileSync(path.join(root,'app.js'),'window.app=true');const config={routes:[],assets:[]},plan=planStaticPreview({project:root,file:'pages/index.html',id:'first',config});assert.deepEqual(plan.inputs.map(x=>x.path),['app.js','icon.svg','pages/index.html','site.css']);assert(plan.assets.some(x=>x.path==='/preview/first/site.css'));const existing=planStaticPreview({project:root,file:'pages/index.html',id:'ignored',config:{routes:[{path:'/custom/page/',file:'pages/index.html'}],assets:[]}});assert.equal(existing.route,'/custom/page/');assert.throws(()=>planStaticPreview({project:root,file:'pages/index.html',id:'first',config:{routes:[{path:plan.route,file:'other.html'}],assets:[]}}),/冲突/);fs.writeFileSync(path.join(root,'pages/index.html'),'<script src="../../escape.js"></script>');assert.throws(()=>planStaticPreview({project:root,file:'pages/index.html',id:'first',config}));});
test('047R3 compiler import contract accepts hook aliases and rejects DOM default/namespace and unknown React API before iframe',()=>{const root=temp();const make=code=>{fs.writeFileSync(path.join(root,'View.jsx'),code);const d=analyzeSourcesInWorker({project:root,entryRoots:['View.jsx']}).definitions.find(d=>d.name==='View');const asset={id:'view',assetModel:{binding:{file:d.file,export:'View',declarationKind:d.declarationKind,anchor:d.anchor}}};return ()=>prepareSourceScene({project:root,facts:{components:{items:[asset]}},asset,scenario:{id:'default',definitionId:'view'}})};assert(make("import {useState as state} from 'react';export function View(){const [n]=state(0);return <p>{n}</p>}")());for(const code of ["import DOM from 'react-dom/client';export function View(){return <p/>}","import * as DOM from 'react-dom/client';export function View(){return <p/>}","import {unknownAPI} from 'react';export function View(){return <p/>}","export * from 'react';export function View(){return <p/>}"])assert.throws(make(code),/不支持/);});

test('047R3 a runtime-referenced document cannot receive a documentation exclusion',()=>{const root=temp();fs.writeFileSync(path.join(root,'app.js'),"fetch('./copy.md')");fs.writeFileSync(path.join(root,'copy.md'),'运行文案');fs.writeFileSync(path.join(root,'guide.md'),'独立说明');const captured=captureProjectRoundInputs(root),state=advanceProjectObservation(null,captured);assert.equal(captured.files.find(file=>file.path==='copy.md').kind,'runtime-candidate');assert(state.pendingChanges.some(change=>change.path==='copy.md'));assert(!state.exclusions.some(file=>file.path==='copy.md'));assert(state.exclusions.some(file=>file.path==='guide.md'));});

test('047R3 exact acceptance cannot borrow another owner evidence in a shared scope',()=>{const task={id:'task',deliveryScope:{revision:1},evidenceIndex:[{evidenceId:'one',taskId:'task',scopeRevision:1,subject:{definitionId:'owner-a'},dimensions:DELIVERY_DIMENSIONS}]},results={one:{state:'verified',result:'passed'}};assert(hasCurrentOwnerEvidence('owner-a',task,results));assert(!hasCurrentOwnerEvidence('owner-b',task,results));assert(!hasCurrentOwnerEvidence('owner-a',task,{one:{state:'stale',result:'passed'}}));task.evidenceIndex[0].scopeRevision=0;assert(!hasCurrentOwnerEvidence('owner-a',task,results));});

test('047R3 inline modules include local dependencies and reserve the product bridge route',()=>{const root=temp();fs.writeFileSync(path.join(root,'index.html'),'<main>模块页面</main><script type="module">import "./app.js";</script>');fs.writeFileSync(path.join(root,'app.js'),'window.value=1');assert(planStaticPreview({project:root,file:'index.html',id:'module',config:{}}).inputs.some(input=>input.path==='app.js'));assert.throws(()=>planStaticPreview({project:root,file:'index.html',id:'module',config:{assets:[{path:'/__foundation/standard-preview/preview-bridge.mjs',file:'app.js'}]}}),/冲突/);});

test('047R3 namespace escapes cannot hide unsupported API until iframe execution',()=>{const root=temp();for(const body of ["const R=React;return R.unknown()", "const {unknown}=React;return unknown()"]){fs.writeFileSync(path.join(root,'View.jsx'),"import React from 'react';export function View(){"+body+"}");const d=analyzeSourcesInWorker({project:root,entryRoots:['View.jsx']}).definitions.find(d=>d.name==='View'),asset={id:'view',assetModel:{binding:{file:d.file,export:'View',declarationKind:d.declarationKind,anchor:d.anchor}}};assert.throws(()=>prepareSourceScene({project:root,facts:{components:{items:[asset]}},asset,scenario:{id:'default',definitionId:'view'}}),/不受支持/);}});
